### ISSUE TITLE
Release notes for 1.0.8

### ISSUE THREAD

**Issue by qianmoQ** [EdurtIO/incubator-gcm#26]
**Release time**

`2021-02-28`

**Components involved**

- Netty

**Check list**

- [x] Rebuilding object based routing buffer
- [x] Refactoring the parsing method of client request parameters
- [x] Fix new String(byte[]) DM_DEFAULT_ENCODING
- [x] Fix ParameterDispatcher file conflict
- [x] Fix `@PathVariable` not working [issues-24](https://github.com/EdurtIO/incubator-gcm/issues/24)
- [x] Support freemaker based view [issues-19](https://github.com/EdurtIO/incubator-gcm/issues/19)
- [x] Rename PathHandler to HttpPathHandler
- [x] Fix Error message oversimplification On netty [issues-22](https://github.com/EdurtIO/incubator-gcm/issues/22)
